//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arwa_0522093
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int users_id { get; set; }
        public string users_name { get; set; }
        public string user_password { get; set; }
        public Nullable<int> age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string city { get; set; }
    }
}
